/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "alert-color": "var(--alert-color)",
        "alert-text-color": "var(--alert-text-color)",
        "danger-color": "var(--danger-color)",
        "danger-text-color": "var(--danger-text-color)",
        "dark-background-color": "var(--dark-background-color)",
        "disabled-element-color": "var(--disabled-element-color)",
        "disabled-element-text-color": "var(--disabled-element-text-color)",
        "faded-primary-color": "var(--faded-primary-color)",
        "faded-secondary-color-1": "var(--faded-secondary-color-1)",
        "faded-secondary-color-2": "var(--faded-secondary-color-2)",
        "hover-color": "var(--hover-color)",
        "hover-text-color": "var(--hover-text-color)",
        "light-background": "var(--light-background)",
        "light-background-color": "var(--light-background-color)",
        "light-gray-1": "var(--light-gray-1)",
        "light-gray-2": "var(--light-gray-2)",
        "light-text-color": "var(--light-text-color)",
        "light-text-gray-1": "var(--light-text-gray-1)",
        "light-text-gray-2": "var(--light-text-gray-2)",
        "muted-color": "var(--muted-color)",
        "muted-text-color": "var(--muted-text-color)",
        "primary-color": "var(--primary-color)",
        "primary-text-color": "var(--primary-text-color)",
        "second-text-color": "var(--second-text-color)",
        "secondary-color-1": "var(--secondary-color-1)",
        "secondary-color-2": "var(--secondary-color-2)",
        "secondary-text-color-1": "var(--secondary-text-color-1)",
        "secondary-text-color-2": "var(--secondary-text-color-2)",
        "success-color": "var(--success-color)",
        "success-text-color": "var(--success-text-color)",
        "text-color": "var(--text-color)",
      },
      fontFamily: {
        "btn-text": "var(--btn-text-font-family)",
        "h-0": "var(--h-0-font-family)",
        "h-1": "var(--h-1-font-family)",
        "h-2": "var(--h-2-font-family)",
        "h-3": "var(--h-3-font-family)",
        "h-4": "var(--h-4-font-family)",
        "h-5": "var(--h-5-font-family)",
        "h-6": "var(--h-6-font-family)",
        link: "var(--link-font-family)",
        list: "var(--list-font-family)",
        "mobile-menu": "var(--mobile-menu-font-family)",
        paragraph: "var(--paragraph-font-family)",
        small: "var(--small-font-family)",
      },
      boxShadow: {
        "accentued-drop-shadow": "var(--accentued-drop-shadow)",
        "dramatic-shadow": "var(--dramatic-shadow)",
        "light-drop-shadow": "var(--light-drop-shadow)",
        "text-shadow": "var(--text-shadow)",
      },
    },
  },
  plugins: [],
};
